spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
          # When built with vscode the a target folder is created with a classes subfolder that corresponds to 'classpath:/' and contains a copy of the 'resources' folder
            - classpath:/configuration/ecom
  # rabbitmq:
  #   host: "{cipher}5b25c84ba3348e568ec5f7ad16e4943cc41f2e4afdbdbddbb078ce327015333fa0af9f541e309357b98f9de89a773ccb"
  #   port: 5672
  #   username: "{cipher}09b1cf26f59ef0c5f5ce575c593c24fa3da9f34772e1e0a32696db4bb8f1aaac"
  #   password: "{cipher}c50d023c07c06f646fe442fe7ac4a0803980af49b7fafc9f52ab5c02fd79d23325562bfea2c51594350c387a821fcbf815b0f783a2b657d8384dd066b0a710fd"
  #   virtual-host: "{cipher}09b1cf26f59ef0c5f5ce575c593c24fa3da9f34772e1e0a32696db4bb8f1aaac"
  #   connection-timeout: 3000
  

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${CONFIG_SERVER_PORT}

encrypt:
  key: ${CONFIG_SERVER_AES_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true