spring:  
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Circuit breaker
# See https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 5
        waitDuration: 1000ms
  ratelimiter:
    instances:
      orderServiceLimiter:
        # See https://resilience4j.readme.io/docs/ratelimiter#create-and-configure-a-ratelimiter
        timeout-duration: 0 # Not waiting before failure if the rate is reached and request arrives
        limit-for-period: 2 # Number of API calls in a specific period of time
        limit-refresh-period: 4s # The time period told in the previous parameter
