spring:
  datasource:
    url: "jdbc:postgresql://ep-hidden-grass-ablxy9d1-pooler.eu-west-2.aws.neon.tech/orders?sslmode=require&channel_binding=require"
    username: neondb_owner
    password: npg_cuJfGQLOXU84
