spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # - id: product-service
            #   uri: lb://ecom-product-microservice
            #   predicates:
            #     - Path=/api/products/**
            #   filters:
            #     - Name=gatewayBreaker
            - id: user-service
              uri: lb://ecom-user-microservice
              predicates:
                - Path=/api/users/**
            - id: order-service
              uri: lb://ecom-order-microservice
              predicates:
                - Path=/api/orders/**, /api/cart/**
            - id: eureka-server
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/main
              filters:
                - SetPath=/
            - id: eureka-server-static
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      gatewayBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
